import type { WorldKnowledgeData } from './world.types'

/**
 * 仅用于主线程接入时快速预览组件结构；真实页面可直接替换为服务端或 store 数据。
 */
export const WORLD_KNOWLEDGE_EXAMPLE: WorldKnowledgeData = {
  nodes: [
    {
      id: 'ten-suns',
      eyebrow: '核心法则 / 01',
      title: '十日轮',
      summary: '十枚日轮记录每一局的终点，熄灭并不等于结束。',
      detail: '日轮是世界的公共时钟，也是所有玩家都能观察到的规则锚点。它的缺口会改变下一局的记忆权重。',
      kind: 'lore',
      status: 'known',
      tags: ['十日', '轮回', '规则'],
      linkedNodeIds: ['memory-seal', 'round-table'],
      accent: '#E3C27C',
      clueIds: ['last-sun'],
    },
    {
      id: 'memory-seal',
      eyebrow: '遗物 / 07',
      title: '骨白中央牌',
      summary: '一张没有花色的牌，保存着上一局无人承认的选择。',
      detail: '中央牌不会主动给出答案，但会把被忽略的选择重新投影到下一次发牌之前。',
      kind: 'relic',
      status: 'unstable',
      tags: ['中央牌', '回放', '记忆'],
      linkedNodeIds: ['ten-suns', 'round-table'],
      accent: '#4ECB9C',
      clueIds: ['unclaimed-choice'],
    },
    {
      id: 'round-table',
      eyebrow: '地景 / 03',
      title: '升桌之境',
      summary: '牌局发生的圆桌会把玩家的动作留下，形成可回看的金色路径。',
      detail: '圆桌不是舞台布景，而是世界观测玩家的界面。每一条回响线都会成为后续事件的触发条件。',
      kind: 'place',
      status: 'known',
      tags: ['圆桌', '回响线', '观测'],
      linkedNodeIds: ['ten-suns', 'memory-seal', 'echo-faction'],
      accent: '#8B93F8',
      clueIds: ['golden-trace'],
    },
    {
      id: 'echo-faction',
      eyebrow: '阵营 / 02',
      title: '回响庭',
      summary: '他们收集被遗忘的动作，试图让世界只保留一种正确答案。',
      detail: '回响庭相信稳定比自由更重要，因此会主动抹平矛盾的事件记录。',
      kind: 'faction',
      status: 'sealed',
      tags: ['庭院', '裁决', '抹除'],
      linkedNodeIds: ['round-table', 'memory-seal'],
      accent: '#EE6A72',
      clueIds: ['silent-verdict'],
    },
  ],
  events: [
    {
      id: 'event-sun-gap',
      title: '第七枚日轮出现空响',
      summary: '倒计时继续，但中央牌面没有生成对应的熄灭记录。',
      occurredAt: '刚刚',
      severity: 'warning',
      nodeIds: ['ten-suns', 'memory-seal'],
      detail: '系统暂时把空响归类为观测误差，回响庭的记录却提前封存了它。',
      isUnread: true,
    },
    {
      id: 'event-golden-trace',
      title: '金色回响线绕过桌沿',
      summary: '一条新路径连接了升桌之境与已封存的阵营记录。',
      occurredAt: '12 分钟前',
      severity: 'signal',
      nodeIds: ['round-table', 'echo-faction'],
      detail: '路径终点尚未显形，暂时只能确认它经过中央牌。',
    },
    {
      id: 'event-memory-rewrite',
      title: '上一局的选择被重新投影',
      summary: '一名玩家的弃牌动作，在本局开场再次出现。',
      occurredAt: '1 小时前',
      severity: 'critical',
      nodeIds: ['memory-seal', 'round-table'],
      detail: '这不是回放。投影改变了本局的可用线索顺序。',
    },
  ],
  clues: [
    {
      id: 'last-sun',
      label: 'CLUE-01',
      title: '没有熄灭的那一日',
      quote: '规则没有消失，只是暂时不承认自己发生过。',
      body: '日轮缺口与中央牌的空白同时出现。若两者存在因果关系，下一局的终点可能会被玩家提前看见。',
      nodeIds: ['ten-suns', 'memory-seal'],
      state: 'unread',
    },
    {
      id: 'unclaimed-choice',
      label: 'CLUE-02',
      title: '无人承认的选择',
      quote: '被放弃的牌，仍然记得谁先松手。',
      body: '中央牌保存了一段无法归属的动作记录。它只在事件流发生偏移时短暂显形。',
      nodeIds: ['memory-seal', 'round-table'],
      state: 'open',
    },
    {
      id: 'golden-trace',
      label: 'CLUE-03',
      title: '桌沿之外的路径',
      body: '回响线没有在圆桌边缘断开，而是向封存区延伸。它可能是一个新阵营，也可能是被抹掉的旧规则。',
      nodeIds: ['round-table', 'echo-faction'],
      state: 'verified',
    },
    {
      id: 'silent-verdict',
      label: 'CLUE-04',
      title: '无声裁决',
      body: '回响庭没有发布任何公告，却先一步修改了事件的可见范围。',
      nodeIds: ['echo-faction'],
      state: 'unread',
    },
  ],
}

